### ISSUE TITLE
Improve custom repository template to support customized EfCoreDbContext

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#104] opened 2020-08-09 10:05 UTC
See:
* https://docs.abp.io/en/abp/latest/Entity-Framework-Core#set-base-dbcontext-class-or-interface-for-default-repositories
* https://github.com/abpframework/abp/issues/1429#issuecomment-549879532
* https://github.com/EasyAbp/WeChatManagement/issues/6

**Comment by wakuflair** [comment] 2020-09-10 06:24
Duplicate of #111

**Closed by wakuflair** 2020-09-10 06:24 UTC
